services:
  - type: web
    name: churn-predictor
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python wsgi.py
    envVars:
      - key: PYTHONPATH
        value: .
      - key: FLASK_ENV
        value: production 